---

version: "3"

services:
  healthy:
    image: healthcheck
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: PathPrefix:/
      traefik.backend.healthcheck.path: /
      traefik.backend.healthcheck.interval: 1s

  traefik:
    image: traefik:1.7-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
